### ISSUE TITLE
Use AXIOS to add headers for all fetch

### ISSUE THREAD

**Issue by JWCENTON** [JWCENTON/equip-watch#204]
- AXIOS - Jacek
- loading image - Dawid

**Comment by marcinstodolny** [comment]
LINIA 122 - 140 w środku async function updateDetails()

import Axios from "axios"


try {
    const response = await Axios.get(`${apiUrl}/api/equipment/${detailsData.id}`, {
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        }
    });

    if (response.status === 200) {
        const data = response.data;
        setDetails(data);
        return data.location;
    }
} catch (error) {
    console.error(error);
}
